N = int(input())
A = set(map(lambda x: int(x[:-1]), input()[1:].split()))
B = set(map(lambda x: int(x[:-1]), input()[1:].split()))
print(A.union(B))
print(A.intersection(B))
print(A.difference(B))
print(B.difference(A))
print(set(range(1, N+1)).difference(A))
print(set(range(1, N+1)).difference(B))